Repository TheBlackPlague/StockNemo, pull requests merged in 2022-09, with the labels that each got.

#67 Introduce a templated-generic Move Search.
  Backend/Board.cs
  Backend/Data/Template/AccumulatorOperation.cs
  Backend/Data/Template/NodeType.cs
  Backend/Engine/MoveSearch.cs
  Backend/Engine/NNUE/Architecture/Basic/BasicNNUE.cs
  Benchmark/NNUE.cs
  Test/NNUE.cs
Labels: enhancement

#68 Add Selective Depth to Engine Output.
  Backend/Engine/MoveSearch.cs
Labels: enhancement

#69 Use Transposition Table in QSearch.
  Backend/Engine/MoveSearch.cs
Labels: enhancement

#70 Implement Approximated Static Exchange Evaluation in QSearch.
  Backend/Engine/MoveSearch.cs
  Backend/Engine/SEE.cs
Labels: enhancement

#71 Search Stack to allow better API for recursive search.
  Backend/Data/MoveSearchStack.cs
  Backend/Data/Struct/MoveSearchStackItem.cs
  Backend/Engine/MoveSearch.cs
Labels: enhancement

#72 Simplify Transposition Table Lookup in QSearch.
  Backend/Engine/MoveSearch.cs
Labels: enhancement

#73 Increase search benchmark sample size.
  Terminal/OpenBenchBenchmark.cs
Labels: enhancement

#74 Improve Transposition Table Replacement Scheme.
  Backend/Data/MoveTranspositionTable.cs
Labels: enhancement

#75 Implement Internal Iterative Reductions.
  Backend/Engine/MoveSearch.cs
Labels: enhancement

#78 Improve Neural Network Operation Cache Locality.
  Backend/Board.cs
  Backend/Engine/NNUE/Architecture/Basic/BasicNNUE.cs
  Backend/Engine/NNUE/Vectorization/NN.cs
  Benchmark/NNUE.cs
Labels: enhancement, nnue

#80 Implement Hybrid Data Neural Network.
  Backend/Backend.csproj
  Backend/Engine/Evaluation.cs
  Backend/Engine/NNUE/Model/BasicNNUE-02a9cfe493.nnue
  Backend/Engine/NNUE/Model/BasicNNUE-6d53b38dcf.nnue
Labels: enhancement, nnue

#81 Implement Transposition Table Entry Priority.
  Backend/Data/MoveTranspositionTable.cs
Labels: enhancement

#83 Templated Make Move for Normal, Classical, and NN Updates.
  Backend/Board.cs
  Backend/Data/Struct/BitBoardMap.cs
  Backend/Data/Struct/MoveList.cs
  Backend/Data/Template/MoveUpdateType.cs
  Backend/Engine/EngineBoard.cs
  Backend/Engine/MoveSearch.cs
  Backend/Perft.cs
  Test/BitBoardMap.cs
  Test/MoveList.cs
Labels: enhancement

#84 Update History Heuristics on Beta Cutoffs.
  Backend/Data/Struct/OrderedMoveList.cs
  Backend/Engine/MoveSearch.cs
Labels: enhancement

#85 Increase neural network training batch size & reliance on game result.
  Backend/Backend.csproj
  Backend/Engine/Evaluation.cs
  Backend/Engine/NNUE/Model/BasicNNUE-02a9cfe493.nnue
  Backend/Engine/NNUE/Model/BasicNNUE-d604f288bd.nnue
Labels: enhancement, nnue

#87 Decrease learning rate and drop learning rate during Neural Network Training.
  Backend/Backend.csproj
  Backend/Engine/Evaluation.cs
  Backend/Engine/NNUE/Model/BasicNNUE-0334adf934.nnue
  Backend/Engine/NNUE/Model/BasicNNUE-d604f288bd.nnue
Labels: enhancement, nnue

#88 Decrement History Heuristic Scores for non-best moves.
  Backend/Engine/MoveSearch.cs
Labels: enhancement

#90 Fix Illegal En Passant.
  Backend/Data/Struct/MoveList.cs
Labels: enhancement, bugfix
